CREATE DATABASE MediBuddy;
USE MediBuddy;
CREATE TABLE schemes (
    scheme_id INT PRIMARY KEY,
    scheme_name VARCHAR(255) NOT NULL,
    min_age INT,
    max_age INT,
    income_limit DECIMAL(12,2),
    gender VARCHAR(20)
);
INSERT INTO schemes
(scheme_id, scheme_name, min_age, max_age, income_limit, gender)
VALUES

(1, 'Ayushman Bharat (PM-JAY)', 0, NULL, NULL, NULL),
(2, 'Ayushman Vay Vandana Yojana', 70, NULL, NULL, NULL),
(3, 'Employees State Insurance Scheme (ESIC)', 18, 60, 252000, NULL),
(4, 'Janani Suraksha Yojana (JSY)', 18, 49, NULL, 'Female'),
(5, 'Janani Shishu Suraksha Karyakram (JSSK)', 18, 49, NULL, 'Female'),
(6, 'Rashtriya Bal Swasthya Karyakram (RBSK)', 0, 18, NULL, NULL),
(7, 'Rashtriya Kishor Swasthya Karyakram (RKSK)', 10, 19, NULL, NULL),
(8, 'Menstrual Hygiene Scheme (MHS)', 10, 19, NULL, 'Female'),

(9, 'Pradhan Mantri Ayushman Bharat Health Infrastructure Mission (PM-ABHIM)', NULL, NULL, NULL, NULL),
(10, 'Central Government Health Scheme (CGHS)', NULL, NULL, NULL, NULL),
(11, 'Rashtriya Arogya Nidhi (RAN)', NULL, NULL, NULL, NULL),
(12, 'Health Minister''s Discretionary Grant (HMDG)', NULL, NULL, NULL, NULL),
(13, 'National Health Mission (NHM)', NULL, NULL, NULL, NULL),
(14, 'National Rural Health Mission (NRHM)', NULL, NULL, NULL, NULL),
(15, 'National Urban Health Mission (NUHM)', NULL, NULL, NULL, NULL),
(16, 'Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)', NULL, NULL, NULL, NULL),
(17, 'National AYUSH Mission (NAM)', NULL, NULL, NULL, NULL),
(18, 'Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)', 18, 49, NULL, 'Female'),
(19, 'SUMAN (Surakshit Matritva Aashwasan)', 18, NULL, NULL, 'Female'),
(20, 'LaQshya', 18, 49, NULL, 'Female'),
(21, 'Universal Immunization Programme (UIP)', 0, NULL, NULL, NULL),
(22, 'Mission Indradhanush', 0, 2, NULL, 'Female'),
(23, 'Intensified Mission Indradhanush (IMI)', 0, 2, NULL, 'Female'),
(24, 'School Health and Wellness Programme (SHWP)', NULL, NULL, NULL, NULL),
(25, 'Maternal, Perinatal and Child Death Surveillance and Response (MPCDSR)', NULL, NULL, NULL, NULL),
(26, 'Weekly Iron and Folic Acid Supplementation (WIFS)', 10, 19, NULL, NULL),
(27, 'Mission Poshan 2.0', 0, NULL, NULL, 'Female'),
(28, 'Saksham Anganwadi', 0, NULL, NULL, 'Female'),
(29, 'Anaemia Mukt Bharat (AMB)', 0.5, 49, NULL, 'Female'),
(30, 'National Iodine Deficiency Disorders Control Programme (NIDDCP)', NULL, NULL, NULL, NULL),
(31, 'National Tuberculosis Elimination Programme (NTEP)', NULL, NULL, NULL, NULL),
(32, 'National AIDS Control Programme (NACP)', NULL, NULL, NULL, NULL),
(33, 'National Leprosy Eradication Programme (NLEP)', NULL, NULL, NULL, NULL),
(34, 'National Vector Borne Disease Control Programme (NVBDCP)', NULL, NULL, NULL, NULL),
(35, 'National Viral Hepatitis Control Programme (NVHCP)', NULL, NULL, NULL, NULL),
(36, 'National Rabies Control Programme (NRCP)', NULL, NULL, NULL, NULL),
(37, 'Integrated Disease Surveillance Programme (IDSP)', NULL, NULL, NULL, NULL),
(38, 'Integrated Health Information Platform (IHIP)', NULL, NULL, NULL, NULL),
(39, 'National Programme on Antimicrobial Resistance (AMR) Containment', NULL, NULL, NULL, NULL),
(40, 'National One Health Programme', NULL, NULL, NULL, NULL),
(41, 'National Zoonoses Programme', NULL, NULL, NULL, NULL),
(42, 'National Programme for Prevention and Control of Non-Communicable Diseases (NP-NCD)', 30, NULL, NULL, NULL),
(43, 'National Cancer Control Programme (NCCP)', NULL, NULL, NULL, NULL),
(44, 'National Tobacco Control Programme (NTCP)', NULL, NULL, NULL, NULL),
(45, 'National Programme for Health Care of the Elderly (NPHCE)', 60, NULL, NULL, NULL),
(46, 'National Programme for Palliative Care (NPPC)', NULL, NULL, NULL, NULL),
(47, 'National Programme for Prevention and Management of Burn Injuries (NPPMBI)', NULL, NULL, NULL, NULL),
(48, 'National Mental Health Programme (NMHP)', NULL, NULL, NULL, NULL),
(49, 'District Mental Health Programme (DMHP)', NULL, NULL, NULL, NULL),
(50, 'Tele-MANAS (Tele Mental Health Assistance and Networking Across States)', NULL, NULL, NULL, NULL),
(51, 'National Programme for Control of Blindness and Visual Impairment (NPCBVI)', NULL, NULL, NULL, NULL),
(52, 'National Programme for Prevention and Control of Deafness (NPPCD)', NULL, NULL, NULL, NULL),
(53, 'ABHA (Ayushman Bharat Health Account) Health ID', NULL, NULL, NULL, NULL),
(54, 'eSanjeevani', NULL, NULL, NULL, NULL),
(55, 'eHospital', NULL, NULL, NULL, NULL),
(56, 'Personal Health Record (PHR)', NULL, NULL, NULL, NULL),
(57, 'National Medical Register (NMR)', NULL, NULL, NULL, NULL),
(58, 'U-WIN', 0, 17, NULL, 'Female'),
(59, 'Nikshay', NULL, NULL, NULL, NULL),
(60, 'Health Management Information System (HMIS)', NULL, NULL, NULL, NULL),
(61, 'Pradhan Mantri Bhartiya Janaushadhi Pariyojana (PMBJP)', NULL, NULL, NULL, NULL),
(62, 'Free Drugs Service Initiative (FDSI)', NULL, NULL, NULL, NULL),
(63, 'Free Diagnostics Service Initiative (FDSI)', NULL, NULL, NULL, NULL),
(64, 'National Organ Transplant Programme (NOTP)', NULL, NULL, NULL, NULL),
(65, 'National Dialysis Programme (NDP)', NULL, NULL, NULL, NULL),
(66, 'Emergency Care Centre Scheme', NULL, NULL, NULL, NULL),
(67, 'National Trauma Care Programme', NULL, NULL, NULL, NULL),
(68, 'Indian Public Health Standards (IPHS)', NULL, NULL, NULL, NULL),
(69, 'National Family Welfare Programme', NULL, NULL, NULL, NULL),
(70, 'Family Planning Programme', NULL, NULL, NULL, NULL),
(71, 'Mission Parivar Vikas', NULL, NULL, NULL, NULL),
(72, 'Eat Right India', NULL, NULL, NULL, NULL),
(73, 'Food Safety Compliance System (FoSCoS)', NULL, NULL, NULL, NULL),
(74, 'Safe and Nutritious Food (SNF) Initiative', NULL, NULL, NULL, NULL),
(75, 'AYUSH Public Health Programme', NULL, NULL, NULL, NULL),
(76, 'Ayush Gram', NULL, NULL, NULL, NULL),
(77, 'SUPRAJA', NULL, NULL, NULL, 'Female'),
(78, 'VAYO MITRA', 60, NULL, NULL, NULL),
(79, 'AYURVIDYA', NULL, NULL, NULL, NULL),
(80, 'AYUSH Mobile Medical Unit (AMMU)', NULL, NULL, NULL, NULL),
(81, 'KARUNYA', NULL, NULL, NULL, NULL),
(82, 'AYUSH School Health Programme', NULL, NULL, NULL, NULL),
(83, 'National Programme on AYUSH for Morbidity Management and Disability Prevention (MMDP)', NULL, NULL, NULL, NULL),
(84, 'Integration of AYUSH with NP-NCD', 30, NULL, NULL, NULL),
(85, 'National Centre for Disease Control (NCDC) Initiatives', NULL, NULL, NULL, NULL),
(86, 'National Cold Chain and Vaccine Management Programme', NULL, NULL, NULL, NULL),
(87, 'Integrated Public Health Laboratories (IPHL) Scheme', NULL, NULL, NULL, NULL),
(88, 'National Programme on Climate Change and Human Health (NPCCHH)', NULL, NULL, NULL, NULL),
(89, 'Kilkari', NULL, NULL, NULL, 'Female'),
(90, 'Mobile Academy', NULL, NULL, NULL, NULL),
(91, 'Healthcare Workforce Mobility Initiative', NULL, NULL, NULL, NULL),
(92, 'OxyCare Management Information System', NULL, NULL, NULL, NULL),
(93, 'NextGen eHospital', NULL, NULL, NULL, NULL),
(94, 'CDSCO Online Licensing System (SUGAM Portal)', NULL, NULL, NULL, NULL),
(95, 'Pharmacovigilance Programme of India (PvPI)', NULL, NULL, NULL, NULL),
(96, 'Materiovigilance Programme of India (MvPI)', NULL, NULL, NULL, NULL),
(97, 'Haemovigilance Programme of India (HvPI)', NULL, NULL, NULL, NULL),
(98, 'Biovigilance Programme of India (BvPI)', NULL, NULL, NULL, NULL),

(99, 'National Programme for Prevention and Control of Fluorosis (NPPCF)', 0, NULL, NULL, NULL),
(100, 'National Programme for Prevention and Control of Occupational Diseases (NPPCOD)', 0, NULL, NULL, NULL),
(101, 'National Programme for Prevention and Control of Deafness in Children', 0, 18, NULL, NULL),
(102, 'National Programme for Prevention and Control of Human Rabies', 0, NULL, NULL, NULL),
(103, 'National Programme for Prevention and Control of Snakebite Envenoming', 0, NULL, NULL, NULL),
(104, 'Universal Screening for Hypertension and Diabetes Initiative', 30, NULL, NULL, NULL),
(105, 'Intensified Diarrhoea Control Fortnight (IDCF)', 0, 5, NULL, NULL),
(106, 'National Deworming Programme (National Deworming Day)', 1, 19, NULL, NULL),
(107, 'Intensified Pulse Polio Programme', 0, 5, NULL, NULL),
(108, 'National Blood Transfusion Services Programme (NBTS)', 0, NULL, NULL, NULL),
(109, 'National Blood Donor Vigilance Programme', 18, 65, NULL, NULL),
(110, 'National Haemophilia Programme', 0, NULL, NULL, NULL),
(111, 'National Thalassaemia Control Programme', 0, NULL, NULL, NULL),
(112, 'National Sickle Cell Anaemia Elimination Mission', 0, 40, NULL, NULL),
(113, 'National Policy for Rare Diseases Support Scheme', 0, NULL, NULL, NULL),
(114, 'National Programme for Air Pollution and Human Health', 0, NULL, NULL, NULL),
(115, 'National Heat and Health Programme', 0, NULL, NULL, NULL),
(116, 'National Centre for One Health (NCOH)', 0, NULL, NULL, NULL),
(117, 'PM National Dialysis Expansion Initiative', 0, NULL, NULL, NULL),
(118, 'National Free Essential Drugs Programme', 0, NULL, NULL, NULL),
(119, 'National Free Essential Diagnostics Expansion Programme', 0, NULL, NULL, NULL),
(120, 'National Biomedical Waste Management Programme', 0, NULL, NULL, NULL),
(121, 'National Infection Prevention and Control Programme (NIPC)', 0, NULL, NULL, NULL),
(122, 'National Sepsis Management Initiative', 0, NULL, NULL, NULL),
(123, 'National Antimicrobial Stewardship Programme', 0, NULL, NULL, NULL),
(124, 'National Public Health Emergency Operations Centre (PHEOC) Initiative', 0, NULL, NULL, NULL),
(125, 'National Health Emergency Preparedness Programme', 0, NULL, NULL, NULL),
(126, 'National Quality Certification Programme for Public Health Facilities', 0, NULL, NULL, NULL),
(127, 'National Nursing and Midwifery Strengthening Programme', 0, NULL, NULL, NULL),
(128, 'National Emergency Life Support Services Initiative', 0, NULL, NULL, NULL),
(129, 'National Poison Information Programme', 0, NULL, NULL, NULL),
(130, 'National Burn Registry Programme', 0, NULL, NULL, NULL),
(131, 'National Injury Surveillance Programme', 0, NULL, NULL, NULL),
(132, 'National Health Promotion Programme', 0, NULL, NULL, NULL),
(133, 'National School Eye Health Programme', 5, 18, NULL, NULL),
(134, 'National School Oral Health Programme', 5, 18, NULL, NULL),
(135, 'National Health Systems Resource Centre (NHSRC) Support Programme', 0, NULL, NULL, NULL),
(136, 'National Medical College Strengthening Programme', 0, NULL, NULL, NULL),
(137, 'National Public Health Cadre Support Programme', 0, NULL, NULL, NULL),
(138, 'National Biosecurity Preparedness Programme', 0, NULL, NULL, NULL),
(139, 'National Health Research Capacity Building Programme', 0, NULL, NULL, NULL),
(140, 'National Disease Elimination Surveillance Programme', 0, NULL, NULL, NULL),
(141, 'National Pandemic Preparedness Programme', 0, NULL, NULL, NULL),
(142, 'National Integrated Vector Surveillance Programme', 0, NULL, NULL, NULL),
(143, 'National Health Emergency Response Network', 0, NULL, NULL, NULL),
(144, 'National Community Health Officer (CHO) Programme', 0, NULL, NULL, NULL),
(145, 'National Digital Public Health Platform Initiative', 0, NULL, NULL, NULL);
alter table schemes 
add state varchar(255);
alter table schemes
add Description TEXT;